{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7c53b0b-e109-45b2-b0b3-d8e54ff48b75",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mysql.connector\n",
    "\n",
    "def create_database():\n",
    "    # Connect to the default database\n",
    "    conn = mysql.connector.connect(\n",
    "        host=\"127.0.0.1\",\n",
    "        user=\"root\",\n",
    "        password=\"1234\"\n",
    "    )\n",
    "    conn.autocommit = True\n",
    "    curr = conn.cursor()\n",
    "\n",
    "    # Drop and create the projectp0 database\n",
    "    curr.execute(\"DROP DATABASE IF EXISTS projectp0\")\n",
    "    curr.execute(\"CREATE DATABASE projectp0\")\n",
    "\n",
    "    # Close connection to the default database\n",
    "    curr.close()\n",
    "    conn.close()\n",
    "\n",
    "    # Connect to the projectp0 database\n",
    "    conn = mysql.connector.connect(\n",
    "        host=\"127.0.0.1\",\n",
    "        user=\"root\",\n",
    "        password=\"1234\",\n",
    "        database=\"projectp0\"\n",
    "    )\n",
    "    curr = conn.cursor()\n",
    "\n",
    "    return curr, conn\n",
    "\n",
    "def create_tables(curr, conn):\n",
    "    try:\n",
    "        # Create tables\n",
    "        customer_table_create = \"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS Customer (\n",
    "            customer_id INT PRIMARY KEY,\n",
    "            customer_name VARCHAR(255),\n",
    "            country VARCHAR(100),\n",
    "            city VARCHAR(100)\n",
    "        );\n",
    "        \"\"\"\n",
    "        curr.execute(customer_table_create)\n",
    "        conn.commit()\n",
    "\n",
    "        product_table_create = \"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS Product (\n",
    "            product_id INT PRIMARY KEY,\n",
    "            product_name VARCHAR(255),\n",
    "            product_category VARCHAR(100),\n",
    "            price DECIMAL(10, 2),\n",
    "            ecommerce_website_name VARCHAR(255)\n",
    "        );\n",
    "        \"\"\"\n",
    "        curr.execute(product_table_create)\n",
    "        conn.commit()\n",
    "\n",
    "        order_table_create = \"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS Orders (\n",
    "            order_id INT PRIMARY KEY,\n",
    "            customer_id INT,\n",
    "            product_id INT,\n",
    "            qty INT,\n",
    "            datetime TEXT,\n",
    "            FOREIGN KEY (customer_id) REFERENCES Customer(customer_id),\n",
    "            FOREIGN KEY (product_id) REFERENCES Product(product_id)\n",
    "        );\n",
    "        \"\"\"\n",
    "        curr.execute(order_table_create)\n",
    "        conn.commit()\n",
    "\n",
    "        payment_table_create = \"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS Payment (\n",
    "            payment_txn_id VARCHAR(255) PRIMARY KEY,\n",
    "            order_id INT,\n",
    "            payment_type VARCHAR(50),\n",
    "            payment_txn_success CHAR(1),\n",
    "            failure_reason VARCHAR(255),\n",
    "            FOREIGN KEY (order_id) REFERENCES Orders(order_id)\n",
    "        );\n",
    "        \"\"\"\n",
    "        curr.execute(payment_table_create)\n",
    "        conn.commit()\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error creating tables: {e}\")\n",
    "\n",
    "def main():\n",
    "    curr, conn = create_database()\n",
    "    create_tables(curr, conn)\n",
    "\n",
    "    # Close connection\n",
    "    curr.close()\n",
    "    conn.close()\n",
    "    print(\"Database connection closed.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
